---
ip: '192.168.178.64'
modes:
  random:
    type: 'random'
  rotate:
    type: 'rotate'
  christmas:
    type: 'linear'
    colors:
      - red
      - green
colors:
  red: 255, 0, 0
  green: 0, 255, 0
verbose: true