---
ip: '192.168.178.49'
modes:
  random:
    type: 'random'
  rotate:
    type: 'rotate'
  christmas:
    type: 'linear'
    colors:
      - red
      - green
    steps: 50 # default is 10 steps
  wild:
    type: 'linear'
    colors:
      - red
      - green
      - blue
colors:
  red: 255, 0, 0
  green: 0, 255, 0
  blue: 0, 0, 255
verbose: true